export * from './UserPage'
export * from './LoginPage'
export * from './Hero'
export * from './Home'
export * from './CorteClasico'
export * from './AfeitadoTradicional'
export * from './ArregloBarba'
export * from './CorteYBarba'